# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        # for using password_hash.  
    #    Symfony\Component\Security\Core\User\User:
    #         algorithm:      bcrypt
    #         cost:           13

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: "admin"
                        roles: ['ROLE_ADMIN']
                    user:
                        password: "user"
                        roles: ['ROLE_USER']

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        settings:
            pattern: ^/settings/
            anonymous: ~
            logout: ~            
            guard:
                authenticators:
                    - app.settings_authenticator

        main:
            security: false
        
    access_control:
        - { path: ^/settings/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/settings/, roles: ROLE_ADMIN}
            

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
